### ISSUE TITLE
Issues compiling GuruxDLMS: esp-idf framework

### ISSUE THREAD

**Issue by hjaltij** [viric/esphome-ziv#1]
Hi,

Thanks for open sourcing this. Did you not run into problems compiling GuruxDLMS?

I'm seeing:
/GuruxDLMS/development/src/gxserializer.c: In function 'ser_loadVariant':
/GuruxDLMS/development/src/gxserializer.c:910:13: error: implicit declaration of function 'bb_init'; did you mean 'ba_init'? [-Werror=implicit-function-declaration]

Wonder if you had to make configuration changes for that to work.

Thanks.

**Comment by viric** [comment]
Hm I don't remember problems. Today I built it fine I think. What are you running?

**Comment by hjaltij** [comment]
I figured it out. I had `framework` set to `esp-idf`, i.e.:

```
framework:
  type: esp-idf
```

Changing it to the following fixed it.
```
framework:
  type: arduino
```

Unfortunately I don't think my meter is compatible though or it might have encryption. It reports communication errors and timeouts.

**Comment by viric** [comment]
ah I agree, esp-idf doesn't work. It's hard to use that esp-idf in my system somehow (python problems) and I didn't make that extra effort to support it.

**Comment by viric** [comment]
@hjaltij this protocol has encryption. You have to match the password and other parameters. Check the initialisation line https://github.com/viric/esphome-ziv/blob/master/components/ziv/ziv.cpp#L37 that I have hardcoded for my meter.

**Comment by hjaltij** [comment]
Right, I changed the client and server address to match my meter (AM550) from the note I found here: https://www.dlms.dev/connect_to_your_meter/

I tried both the simple auth and no auth without luck. Going to enable full verbose logging and see if I get any data from the meter.

**Comment by hjaltij** [comment]
FWIW I'm using the PiggyMeter which is a really neat little package for this but I bought it without fully checking what protocol my meter uses :)

**Comment by viric** [comment]
I also bought the IR serial connector without knowing anything about what to do next. I imagined it would be some trivial supported thing by Aquaticus component but it turned out all worked different with my counter.

**Comment by hjaltij** [comment]
I see so you are also using the PiggyMeter? Did you configure it as a raw serial device before figuring out your meter? Wondering if you have any tips on how to debug this? :)

Thanks again for the help.

**Comment by viric** [comment]
No no, I'm using an ESP32 board with a 3.3V serial IR. The README tells the exact IR device.
I never explored the PiggyMetter.

**Comment by hjaltij** [comment]
Thanks for the help. I'll close this issue :)

**Comment by rrooggiieerr** [comment]
@hjaltij did you ever make it work with the PiggyMetter? I'm considering ordering one to use with a ZIV 5CTM

**Comment by hjaltij** [comment]
I did not. My provider has now replaced my meter with a meter that has a P1 port so I'm using that instead.
